-- schema definition ------------------------------------------------

create table author (
	id integer generated by default as identity,
	bio varchar(255),
	first_name varchar(255),
	last_name varchar(255),
	primary key (id)
);

create table author_technologiesshe_writes_about (
	author_id integer not null,
 	technologiesshe_writes_about varchar(255)
);

create table book (
	id integer generated by default as identity,
	cover_image_path varchar(255),
	description varchar(255),
	isbn varchar(255),
	number_of_pages integer not null check (number_of_pages>=30),
	publication_date date not null,
	subtitle varchar(255),
	title varchar(255),
	author_id integer not null,
	primary key (id)
);

create table book_prices (
	book_id integer not null,
	book_type varchar(255),
	value decimal(19,2)
);

alter table author_technologiesshe_writes_about 
	add constraint technologies_of_an_author 
	foreign key (author_id) 
	references author;

    
alter table book 
	add constraint author_of_a_book 
	foreign key (author_id) 
	references author;

    
alter table book_prices 
	add constraint book_for_prices 
	foreign key (book_id) 
	references book;
	
-- initial data -----------------------------------------------------

insert into author (first_name, last_name, bio) 
	values ('Rafael', 'Rollo', 'Um dev que adora o que faz tanto quanto o futebol, a música ou qualquer outra manifestação artística através da qual pessoas apaixonadas expressam sua verdade.');
	
insert into author (first_name, last_name, bio) 
	values ('Alberto', 'Souza', 'Eu amo ficar com minha família, adoro esportes e atividade física no geral, estudar e trabalhar =).');
